name: Update YouTube RSS

on:
  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: python rss.py
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

      - name: Save RSS
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/feed.xml
          git commit -m "Update RSS" || exit 0
          git push
